version: 0.2

phases:
  pre_build:
    commands:
      - echo Building Docker image...
      - docker build -t agonzalezo/api-ocr:aws .

  build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "DOCKERHUB_TOKEN" | docker login -u "agonzalezo" --password-stdin
      - docker tag agonzalezo/api-ocr:aws agonzalezo/api-ocr:aws

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker ps -a && docker images
      - docker push agonzalezo/api-ocr:aws
