apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-$API_NAME
  namespace: $NAME_SPACE
  labels:
    microservice: api-$API_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: api-$API_NAME
  template:
    metadata:
      labels:
        microservice: api-$API_NAME
        component: appserver
    spec:
      containers:
        - name: api-$API_NAME
          image: agonzalezo/api-$API_NAME:latest
          imagePullPolicy: Always
          # command:
          #   - "/usr/bin/tail"
          #   - "-f"
          #   - "/dev/null"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: API_NAME
              value: $API_NAME
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "150Mi"
              cpu: "200m"
